
---
apiVersion: v1
kind: Service
metadata:
  name: sample-app-dev
  labels:
    app: sample-app
spec:
  type: NodePort
  selector:
    app: sample-app
  ports:
  - protocol: TCP
    port: 8080
    name: http

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: sample-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sample-app
        env: dev
    spec:
      containers:
      - name: sample-app
        image: gcr.io/green-dispatch-219519/sample-app:v1
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 1
